### ISSUE TITLE
TensorFlow dependency

### ISSUE THREAD

**Issue by visr** [NHDaly/Maps.jl#1]
Cool package! Together with https://github.com/JuliaPlots/GeoMakie.jl it will be great to have proper support for mapping with Makie. If we could hook it up with tiled web maps that would be really cool as well, see for instance https://github.com/yeesian/MapTiles.jl.

Anyway, I'm creating this issue because I was surprised to see a TensorFlow dependency in Project.toml/Manifest.toml, thought it doesn't seem to be used. Perhaps it was added by mistake?

**Comment by NHDaly** [comment]
Haha huh, yeah, that IS weird! It's right there int the Project.toml, but i don't know why i would've done that.. 🤷‍♂!

I'll take it out, thanks. :)


> https://github.com/JuliaPlots/GeoMakie.jl

Oh, cool! Yeah, this seems super relevant! I love the idea of merging these together. :) 👍 In fact, that package could very likely supercede this one entirely

**Comment by NHDaly** [comment]
Fixed in 3111343. :)
